Minimal updates in TSC readme
hiero-ledger/tsc pull request #33
Opened 2024-10-17 06:19 UTC by hendrikebbers

2024-10-17 06:34 UTC, stoqnkpL approved these changes

2024-10-17 18:01 UTC, ryjones requested changes
one last change

2024-10-17 18:01 UTC, ryjones commented on README.md
>  Issues [Home](https://github.com/LFDT-Hiero/tsc/issues)
LFDT-Hiero -> hiero-ledger

2024-10-18 20:01 UTC, ryjones approved these changes

2024-10-22 09:07 UTC, merged