Meeting minutes for Dec 17th 2024
hiero-ledger/tsc pull request #76
Opened 2024-12-20 20:40 UTC by itsbrandondev

These are the minutes from the Hiero TSC call on Dec 17th 2024.

2025-01-07 13:17 UTC, stoqnkpL approved these changes

2025-01-07 13:56 UTC, hendrikebbers requested changes

2025-01-07 13:56 UTC, hendrikebbers commented on minutes/2024-12-17.md
>  - Review of HIP-1037 (https://github.com/hashgraph/hedera-improvement-proposal/pull/1037)
All that should be part of the Agenda. Instead of that the agenda now says "(HIP number to be confirmed)" instead of linking to the individual hips. From my point of view the PR should not change "TSC Attendees", "Guests" and "Agenda" topics

2025-01-14 02:36 UTC, itsbrandondev commented on minutes/2024-12-17.md
>  - Review of HIP-1037 (https://github.com/hashgraph/hedera-improvement-proposal/pull/1037)
i've updated the agenda and attendee lists to remain in tact 👍

2025-01-14 14:38 UTC, hendrikebbers approved these changes

2025-01-14 14:38 UTC, merged